# Generated by Django 5.2.15 on 2026-06-09 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("picture_url", models.URLField(blank=True, verbose_name="Picture URL")),
            ],
            options={
                "verbose_name": "Car type",
                "verbose_name_plural": "Car types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time of last update"
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Model")),
                (
                    "plate_number",
                    models.CharField(max_length=50, unique=True, verbose_name="Plate number"),
                ),
                (
                    "num_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number of seats"
                    ),
                ),
                ("picture_url", models.URLField(blank=True, verbose_name="Picture URL")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_repair", "In repair"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "drivers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="driven_cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Drivers",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="car_orders.cartype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time of last update"
                    ),
                ),
                (
                    "planned_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planned date and time"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500, verbose_name="Address")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Project name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("awaiting_driver", "Awaiting driver"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finished at"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Rejected at"),
                ),
                ("reject_reason", models.TextField(blank=True, verbose_name="Reject reason")),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="car_orders.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_car_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driven_car_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Driver",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_car_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rejected by",
                    ),
                ),
                (
                    "car_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="car_orders.cartype",
                        verbose_name="Requested car type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car order",
                "verbose_name_plural": "Car orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarOrderActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sent", "Sent to admin"),
                            ("approved", "Approved"),
                            ("accepted_by_driver", "Accepted by driver"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=32,
                        verbose_name="Kind",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Payload")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_order_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="car_orders.carorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car order activity",
                "verbose_name_plural": "Car order activities",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"], name="car_orders__order_i_663d18_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DriverShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time of last update"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("busy", "Busy"),
                            ("en_route", "En route"),
                            ("offline", "Offline"),
                        ],
                        db_index=True,
                        default="online",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True, verbose_name="Latitude")),
                ("lng", models.FloatField(blank=True, null=True, verbose_name="Longitude")),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last seen"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Ended at"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="car_orders.car",
                        verbose_name="Shift car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver shift",
                "verbose_name_plural": "Driver shifts",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("driver",),
                        name="one_active_shift_per_driver",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("car",),
                        name="one_active_shift_per_car",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time of last update"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "mileage",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Mileage (km)"),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted by",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="car_orders.car",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle report",
                "verbose_name_plural": "Vehicle reports",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("vehicle", "date")},
            },
        ),
    ]
