# Generated by Django 5.2.15 on 2026-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='address_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Destination latitude'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='address_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Destination longitude'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Estimated duration'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='latest_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest acceptable start'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Origin latitude'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='origin_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Origin longitude'),
        ),
        migrations.AddField(
            model_name='carorder',
            name='service_time',
            field=models.DurationField(blank=True, null=True, verbose_name='On-site service time'),
        ),
        migrations.AlterField(
            model_name='carorder',
            name='planned_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned start date and time'),
        ),
        migrations.AlterField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('awaiting_driver', 'Awaiting driver'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='carorderactivity',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent to admin'), ('approved', 'Approved'), ('accepted_by_driver', 'Accepted by driver'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('released', 'Released by driver'), ('extended', 'Extended'), ('reassigned', 'Reassigned')], max_length=32, verbose_name='Kind'),
        ),
    ]
