# Generated by Django 5.2.15 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0002_carorder_address_lat_carorder_address_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('awaiting_driver', 'Awaiting driver'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
