# Generated by Django 5.2.15 on 2026-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0003_alter_carorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Order id')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('last_seen', models.DateTimeField(verbose_name='Last seen')),
            ],
            options={
                'verbose_name': 'Order live location',
                'verbose_name_plural': 'Order live locations',
            },
        ),
    ]
