# Generated by Django 5.2.15 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0004_orderlivelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlivelocation',
            name='geometry',
            field=models.JSONField(blank=True, null=True, verbose_name='Route geometry'),
        ),
    ]
