# Generated by Django 5.2.15 on 2026-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0005_orderlivelocation_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('order_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Order id')),
                ('driver_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Driver user id')),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('address_lat', models.FloatField(blank=True, null=True)),
                ('address_lng', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated duration (minutes)')),
                ('service_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='On-site time (minutes)')),
                ('planned_datetime', models.DateTimeField(blank=True, null=True)),
                ('latest_start', models.DateTimeField(blank=True, null=True)),
                ('trip_state', models.CharField(choices=[('assigned', 'Assigned'), ('to_client', 'Driving to client'), ('at_client', 'Arrived, waiting for client'), ('in_trip', 'In trip with client'), ('at_destination', 'Arrived at destination'), ('waiting', 'On hold (driver stepped away)'), ('completed', 'Completed')], default='assigned', max_length=20)),
            ],
            options={
                'verbose_name': 'Order meta',
                'verbose_name_plural': 'Order meta',
            },
        ),
    ]
