# Generated by Django 5.2.15 on 2026-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0006_ordermeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='car_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Car id'),
        ),
        migrations.AddField(
            model_name='ordermeta',
            name='car_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Car label'),
        ),
    ]
