# Generated by Django 5.2.15 on 2026-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0007_ordermeta_car_id_ordermeta_car_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='overlay_claimed',
            field=models.BooleanField(default=False, verbose_name='Claimed in our layer'),
        ),
    ]
