# Generated by Django 5.2.15 on 2026-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0008_ordermeta_overlay_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermeta',
            name='trip_state',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('to_client', 'Driving to client'), ('at_client', 'Arrived, waiting for client'), ('in_trip', 'In trip with client'), ('at_destination', 'Arrived at destination'), ('waiting', 'On hold (driver stepped away)'), ('completed', 'Completed'), ('cancelled', 'Cancelled / released')], default='assigned', max_length=20),
        ),
    ]
