# Generated by Django 5.2.15 on 2026-06-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0009_alter_ordermeta_trip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='author_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Author user id'),
        ),
    ]
