# Generated by Django 5.2.15 on 2026-06-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0010_ordermeta_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
    ]
