# Generated by Django 5.2.15 on 2026-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0011_ordermeta_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='departure_reminded',
            field=models.BooleanField(default=False, verbose_name='Departure reminded'),
        ),
    ]
