# Generated by Django 5.2.15 on 2026-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0012_ordermeta_departure_reminded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='parent_order_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Parent order id'),
        ),
    ]
