# Generated by Django 5.2.15 on 2026-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0016_drivershiftstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='car_type_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Car type id'),
        ),
        migrations.AddField(
            model_name='ordermeta',
            name='dispatchable',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ready for dispatch'),
        ),
    ]
