# Generated by Django 5.2.15 on 2026-06-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0017_ordermeta_car_type_id_ordermeta_dispatchable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=False, verbose_name='Auto-dispatch enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True, verbose_name='Updated by (user id)')),
            ],
            options={
                'verbose_name': 'Dispatch settings',
                'verbose_name_plural': 'Dispatch settings',
            },
        ),
    ]
