# Generated by Django 5.2.15 on 2026-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0018_dispatchsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('name', models.CharField(max_length=120, verbose_name='Template name')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='Default order name')),
                ('origin_lat', models.FloatField(blank=True, null=True, verbose_name='Origin latitude')),
                ('origin_lng', models.FloatField(blank=True, null=True, verbose_name='Origin longitude')),
                ('origin_label', models.CharField(blank=True, max_length=500, verbose_name='Origin label')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Destination label')),
                ('address_lat', models.FloatField(blank=True, null=True, verbose_name='Destination latitude')),
                ('address_lng', models.FloatField(blank=True, null=True, verbose_name='Destination longitude')),
                ('car_type_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Car type id (demo)')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated duration (minutes)')),
                ('service_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='On-site service time (minutes)')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Created by (demo user id)')),
            ],
            options={
                'verbose_name': 'Car order template',
                'verbose_name_plural': 'Car order templates',
                'ordering': ['name'],
            },
        ),
    ]
