# Generated by Django 5.2.15 on 2026-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0019_carordertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeta',
            name='excluded_driver_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Drivers excluded from auto-dispatch'),
        ),
    ]
