# Generated by Django 5.2.15 on 2026-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_orders', '0020_ordermeta_excluded_driver_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverposition',
            name='heading',
            field=models.FloatField(blank=True, null=True, verbose_name='Heading'),
        ),
    ]
