# Generated by Django 5.2.15 on 2026-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_orders", "0021_driverposition_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermeta",
            name="driver_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Driver name"),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="driver_phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Driver phone"),
        ),
    ]
