# Generated by Django 5.2.15 on 2026-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_orders", "0022_ordermeta_driver_name_ordermeta_driver_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermeta",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="search_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
