# Generated by Django 5.2.15 on 2026-06-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_orders", "0023_ordermeta_arrived_at_ordermeta_search_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermeta",
            name="dest_address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Destination address"),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="origin_address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Origin address"),
        ),
    ]
