# Generated by Django 5.2.15 on 2026-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_orders", "0024_ordermeta_dest_address_ordermeta_origin_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermeta",
            name="car_type_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Car type name"),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="created_by_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Created by"),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note / purpose"),
        ),
        migrations.AddField(
            model_name="ordermeta",
            name="project_name",
            field=models.CharField(blank=True, max_length=500, verbose_name="Project name"),
        ),
    ]
